const https = require('https');
const fs = require('fs');
const path = require('path');
const os = require('os');

// InstantTLS certificate paths
const CERT_DIR = path.join(os.homedir(), '.instanttls', 'certs');
const DOMAIN = 'myapp.local';

// Check if certificates exist
const certPath = path.join(CERT_DIR, `${DOMAIN}.crt`);
const keyPath = path.join(CERT_DIR, `${DOMAIN}.key`);

if (!fs.existsSync(certPath) || !fs.existsSync(keyPath)) {
  console.error(`
╔══════════════════════════════════════════════════════════════╗
║  ❌ Certificates not found!                                   ║
║                                                              ║
║  Run the following commands first:                           ║
║                                                              ║
║    instanttls init                                           ║
║    instanttls cert ${DOMAIN}                                   ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
`);
  process.exit(1);
}

// Create HTTPS server
const server = https.createServer({
  key: fs.readFileSync(keyPath),
  cert: fs.readFileSync(certPath)
}, (req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/html' });
  res.end(`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>InstantTLS Example</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .card {
      background: white;
      border-radius: 16px;
      padding: 48px;
      box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
      text-align: center;
      max-width: 500px;
    }
    .lock { font-size: 64px; margin-bottom: 24px; }
    h1 { color: #1a1a2e; margin-bottom: 16px; }
    p { color: #4a5568; line-height: 1.6; margin-bottom: 24px; }
    .badge {
      display: inline-block;
      background: #10b981;
      color: white;
      padding: 8px 16px;
      border-radius: 9999px;
      font-weight: 600;
      font-size: 14px;
    }
    code {
      background: #f3f4f6;
      padding: 2px 8px;
      border-radius: 4px;
      font-family: monospace;
    }
  </style>
</head>
<body>
  <div class="card">
    <div class="lock">🔒</div>
    <h1>HTTPS is Working!</h1>
    <p>
      This page is served over <strong>HTTPS</strong> with a trusted certificate
      generated by <strong>InstantTLS</strong>.
    </p>
    <p>
      Domain: <code>${DOMAIN}</code>
    </p>
    <span class="badge">✓ Secure Connection</span>
  </div>
</body>
</html>
  `);
});

const PORT = 443;

server.listen(PORT, () => {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║   🔒 HTTPS Server Running!                                   ║
║                                                              ║
║   Open in browser: https://${DOMAIN}                          ║
║                                                              ║
║   Note: Add to /etc/hosts if not already:                    ║
║   127.0.0.1  ${DOMAIN}                                         ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
`);
});

server.on('error', (err) => {
  if (err.code === 'EACCES') {
    console.error(`
╔══════════════════════════════════════════════════════════════╗
║  ❌ Permission denied for port ${PORT}                          ║
║                                                              ║
║  Run with sudo or use a higher port:                         ║
║    sudo node server.js                                       ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
`);
  } else {
    console.error('Server error:', err);
  }
  process.exit(1);
});
